### ISSUE TITLE
Tag 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#33]
Should wait on #32 then tag so we have a known working version.

**Comment by JohnGiorgi** [comment]
Sure, I can maybe draft release guidelines as well so that we have easy to follow steps.

**Comment by jvwong** [comment]
Tag this according to:

https://github.com/PathwayCommons/semantic-search/blob/1e1d1e4ac174fb099f9e8911e9690bffada60e23/setup.py#L8

**Comment by jvwong** [comment]
@JohnGiorgi is there a best practice for tagging or is it as simple as syncing with setup.py ?

**Comment by JohnGiorgi** [comment]
Hi @jvwong, because we aren't pushing it to an index like PyPI, I think all we have to do is tag it in the GitHub repo. I did that here: https://github.com/PathwayCommons/semantic-search/releases/tag/v0.1.0.

But yeah, in the future I think the workflow will be:

1. Bump `version` in `setup.py`
2. Create a release with the tag and name `v{version}`.

**Comment by JohnGiorgi** [comment]
I added these instructions to `setup.py`, just so we have them written down somewhere.

**Comment by jvwong** [comment]
Thanks!
